# Generated by Django 3.0.14 on 2023-06-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
